# Generated by Django 5.2.4 on 2025-07-29 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('initial_value', models.FloatField(help_text='Initial value of the portfolio in USD')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioAssetHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_weight', models.FloatField(help_text='Initial portfolio weight, value must be between 0 and 1)')),
                ('initial_quantity', models.FloatField(help_text='Initial quantity (to be calculated based on price and weight)')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='investments.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='investments.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'asset')},
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField(help_text='Asset price in USD at given date')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='investments.asset')),
            ],
            options={
                'ordering': ['asset', 'date'],
                'unique_together': {('asset', 'date')},
            },
        ),
    ]
